# Clippy ??????
# https://doc.rust-lang.org/clippy/configuration.html

# ?????
max-width = 100

# ????????
too-many-arguments-threshold = 7

# ?????????
too-many-fields-threshold = 10

# ??????
too-many-lines-threshold = 100

# ??????
too-many-nested-blocks-threshold = 4

# ?????
cognitive-complexity-threshold = 25

# ?????
type-complexity-threshold = 250

# ????????
max-struct-bools = 3

# ?????
allowed-idents-below-min-chars = ["i", "j", "x", "y"]

# ??? lint
warn-on-all-wildcard-imports = false
